# Normalizzazione

La normalizzazione è una tecnica di pre-elaborazione dei dati usata per ridimensionare le funzionalità nello stesso intervallo, in genere compreso tra 0 e 1, in modo che possano essere elaborate in modo più accurato da un algoritmo di Machine Learning

<img src="https://frenzy86.s3.eu-west-2.amazonaws.com/python/normalization.png " width="1200">

In [1]:
import pandas as pd
df = pd.DataFrame({
               'A':[1,2,3],
               'B':[100,300,500],
               'C':list('abc')
                })
df

   A    B  C
0  1  100  a
1  2  300  b
2  3  500  c

In [2]:
#nella normalizzazione andiamo a sottrarre ad ogni valore il minimo della colonna, diviso il delta (max-min)

def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

In [3]:
normalize(df[['A','B']])

     A    B
0  0.0  0.0
1  0.5  0.5
2  1.0  1.0

In [4]:
df.describe().T

   count   mean    std    min    25%    50%    75%    max
A    3.0    2.0    1.0    1.0    1.5    2.0    2.5    3.0
B    3.0  300.0  200.0  100.0  200.0  300.0  400.0  500.0

### MinMaxScaler

In [5]:
import pandas as pd
df = pd.DataFrame({
               'A':[1,2,3],
               'B':[100,300,500],
             })
df

   A    B
0  1  100
1  2  300
2  3  500

In [6]:
# Using sklearn
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
arr_scaled = scaler.fit_transform(df)

print(arr_scaled)

df_scaled = pd.DataFrame(arr_scaled, columns=df.columns,index=df.index)
df_scaled

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]

     A    B
0  0.0  0.0
1  0.5  0.5
2  1.0  1.0

In [ ]:
df_scaled.describe().T

   count  mean  std  min   25%  50%   75%  max
A    3.0   0.5  0.5  0.0  0.25  0.5  0.75  1.0
B    3.0   0.5  0.5  0.0  0.25  0.5  0.75  1.0

## Standardizzazione Manuale

La standardizzazione è un altro metodo di scalatura in cui i valori vengono centrati intorno alla media con una deviazione standard unitaria. Ciò significa che la media dell'attributo diventa zero e la distribuzione risultante ha una deviazione standard unitaria

In [7]:
df = pd.DataFrame({
               'A':[1,2,3],
               'B':[100,300,500],
               'C':list('abc')
             })
df

   A    B  C
0  1  100  a
1  2  300  b
2  3  500  c

In [8]:
## Column A --> Mean=0 std=1
df.iloc[:,0:-1] = df.iloc[:,0:-1].apply(lambda x: (x-x.mean())/ x.std(), axis=0)
df

/tmp/ipython-input-851297655.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0   -1.0
1    0.0
2    1.0
Name: A, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[:,0:-1] = df.iloc[:,0:-1].apply(lambda x: (x-x.mean())/ x.std(), axis=0)
/tmp/ipython-input-851297655.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0   -1.0
1    0.0
2    1.0
Name: B, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[:,0:-1] = df.iloc[:,0:-1].apply(lambda x: (x-x.mean())/ x.std(), axis=0)

     A    B  C
0 -1.0 -1.0  a
1  0.0  0.0  b
2  1.0  1.0  c

In [10]:
df.describe().T

   count  mean  std  min  25%  50%  75%  max
A    3.0   0.0  1.0 -1.0 -0.5  0.0  0.5  1.0
B    3.0   0.0  1.0 -1.0 -0.5  0.0  0.5  1.0

## Standardizzazione con Sklearn

In [11]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

df = pd.DataFrame({
               'A':[1,2,3],
               'B':[100,300,500],
               'C':list('abc')
             })
df.iloc[:,0:-1] = ss.fit_transform(df.iloc[:,0:-1])
df

/tmp/ipython-input-1343633704.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.22474487  0.          1.22474487]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[:,0:-1] = ss.fit_transform(df.iloc[:,0:-1])
/tmp/ipython-input-1343633704.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.22474487  0.          1.22474487]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[:,0:-1] = ss.fit_transform(df.iloc[:,0:-1])

          A         B  C
0 -1.224745 -1.224745  a
1  0.000000  0.000000  b
2  1.224745  1.224745  c

In [12]:
df.describe().T

   count  mean       std       min       25%  50%       75%       max
A    3.0   0.0  1.224745 -1.224745 -0.612372  0.0  0.612372  1.224745
B    3.0   0.0  1.224745 -1.224745 -0.612372  0.0  0.612372  1.224745

In [13]:
pd.DataFrame(ss.inverse_transform(df.iloc[:,0:-1] ), columns = ['A','B'])

     A      B
0  1.0  100.0
1  2.0  300.0
2  3.0  500.0

## Veloce

In [16]:
df1 = pd.DataFrame({'Name' : [3, 4,6],
                    'Age' : [18, 92,98],
                    'Weight' : [68, 59,49],
                    })
df1

   Name  Age  Weight
0     3   18      68
1     4   92      59
2     6   98      49

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df1[['Age','Weight']] = scaler.fit_transform(df1[['Age','Weight']])
df1

   Name       Age    Weight
0     3 -1.411004  1.202703
1     4  0.623041  0.042954
2     6  0.787964 -1.245657